name: Comment on Push Commit

on:
  push:
    branches:
      - main

permissions:
  contents: read
  discussions: write #  or contents: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    

    steps:
      - name: Post comment on latest commit
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
            -d '{"body":"🎉 Good job!"}'
