name: Comment on Push

on:
  push:
    branches:
      - main  # or your target branch

permissions:
      contents: write  # required for gh CLI to post comment

jobs:
  comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Comment on the latest commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_SHA=${{ github.sha }}
          gh api \
            -H "Accept: application/vnd.github+json" \
            -X POST \
            /repos/${{ github.repository }}/commits/$COMMIT_SHA/comments \
            -f body="✅ Good job! This commit looks great 👍"
