# This is a basic workflow to help you get started with Actions

name: Create Issue on Push

on:
  push:
    branches: 
      - main
  
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create an issue
        uses: peter-evans/create-issue@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "An issue"
          body: "Hello from issue"

