name: Create Pull Request with hello.txt
on:
  push:
    branches:
      - main
    
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create hello.txt file
        run: echo "github actions" > hello.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add hello.txt file"
          title: "Add hello.txt"
          body: "This PR adds hello.txt file"
          branch: add-hello-file
          base: main
