# This is a basic workflow to help you get started with Actions

name: Create Issue on Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create an issue
        uses: peter-evans/create-issue@v4
        with:
          title: "An issue"
          body: "Hello from issue"

