name: Create Issue on Push

on:
  push:
    branches: 
      - main
  
permissions:
  contents: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: An example issue
          content-filepath: ./txt.txt
          labels: |
            report
            automated issue

