name: Create Pull Request with hello.txt in test directory
on:
  push:
    branches:
      - main
    
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create test directory and hello.txt file
        run: |
          mkdir test
          cd test
          echo "github actions" > hello.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add hello.txt in test directory"
          title: "Add hello.txt in test directory"
          body: "This PR adds test/hello.txt file"
          branch: add-hello-file
          base: main
