name: Create Pull Request with hello.txt

on:
  push:
    branches:
      - main
    
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/aliemre2023/test_action
          cd test_action
    
      - name: Checkout 
        run: git checkout -b hello_branch

      - name: Info init
        run: |
          git config user.name "aliemre2023"
          git config user.email "aliemrekaya239@gmail.com"

      - name: Create hello.txt file
        run: |
          echo "github actions" > hello.txt
          git add hello.txt
          git commit -m "Add hello.txt file"
      
      - name: Push branch
        run: git push origin add-hello-file

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: add-hello-file
          title: "Add hello.txt"
          body: "This PR adds hello.txt file"
