name: Generate TXT and Create PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script to generate output.txt
        run: |
          python code/generate_txt.py
          cat code/generate_txt.py
          echo "---------"
          cat code/output.txt

      - name: Create new branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b auto-output-txt

      - name: Commit generated file
        run: |
          git checkout -b auto-output-txt
          git add output.txt
          git commit -m "Auto-generate output.txt"
          git push --force --set-upstream origin auto-output-txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-generate output.txt
          title: "Auto PR: Generate output.txt"
          body: "This PR was automatically created by GitHub Actions to add the generated output.txt file."
          branch: auto-output-txt
          base: main
