name: Generate PDF Send to PR
on:
  push:
    branches:
      - main
    
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Install dependencies requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Python script
        run: |
          cat code/document.py
          python code/document.py
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add hello.txt file"
          title: "Add hello.txt"
          body: "This PR adds hello.txt file"
          branch: add-hello-file
          base: main